
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TerentievFurnitureStore.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Sale
{

    public int idSale { get; set; }

    public int idClient { get; set; }

    public int idProduct { get; set; }

    public System.DateTime DateOfSale { get; set; }

    public int Quantity { get; set; }

    public decimal Price { get; set; }



    public virtual Client Client { get; set; }

    public virtual Product Product { get; set; }

}

}
