//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerentievFurnitureStore.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerentievFurnitureStore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accept.
        /// </summary>
        public static string BtnAccept {
            get {
                return ResourceManager.GetString("BtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add client.
        /// </summary>
        public static string BtnAddClient {
            get {
                return ResourceManager.GetString("BtnAddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add product.
        /// </summary>
        public static string BtnAddProduct {
            get {
                return ResourceManager.GetString("BtnAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add sale.
        /// </summary>
        public static string BtnAddSale {
            get {
                return ResourceManager.GetString("BtnAddSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clients.
        /// </summary>
        public static string BtnClients {
            get {
                return ResourceManager.GetString("BtnClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate.
        /// </summary>
        public static string BtnGenerate {
            get {
                return ResourceManager.GetString("BtnGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        public static string BtnLogout {
            get {
                return ResourceManager.GetString("BtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Products.
        /// </summary>
        public static string BtnProducts {
            get {
                return ResourceManager.GetString("BtnProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset filtering.
        /// </summary>
        public static string BtnResetFilter {
            get {
                return ResourceManager.GetString("BtnResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sales.
        /// </summary>
        public static string BtnSales {
            get {
                return ResourceManager.GetString("BtnSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        public static string CaptionError {
            get {
                return ResourceManager.GetString("CaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out?.
        /// </summary>
        public static string CaptionExit {
            get {
                return ResourceManager.GetString("CaptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully!.
        /// </summary>
        public static string CaptionSuccessfully {
            get {
                return ResourceManager.GetString("CaptionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        public static string CaptionWarning {
            get {
                return ResourceManager.GetString("CaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string DGAddress {
            get {
                return ResourceManager.GetString("DGAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client.
        /// </summary>
        public static string DGClient {
            get {
                return ResourceManager.GetString("DGClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client ID.
        /// </summary>
        public static string DGClientId {
            get {
                return ResourceManager.GetString("DGClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of birth.
        /// </summary>
        public static string DGDateOfBirth {
            get {
                return ResourceManager.GetString("DGDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of sale.
        /// </summary>
        public static string DGDateOfSale {
            get {
                return ResourceManager.GetString("DGDateOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gender.
        /// </summary>
        public static string DGGender {
            get {
                return ResourceManager.GetString("DGGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sale ID.
        /// </summary>
        public static string DGIdSale {
            get {
                return ResourceManager.GetString("DGIdSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string DGName {
            get {
                return ResourceManager.GetString("DGName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string DGPhone {
            get {
                return ResourceManager.GetString("DGPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string DGPrice {
            get {
                return ResourceManager.GetString("DGPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product.
        /// </summary>
        public static string DGProduct {
            get {
                return ResourceManager.GetString("DGProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product ID.
        /// </summary>
        public static string DGProductId {
            get {
                return ResourceManager.GetString("DGProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production date.
        /// </summary>
        public static string DGProductionDate {
            get {
                return ResourceManager.GetString("DGProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product name.
        /// </summary>
        public static string DGProductName {
            get {
                return ResourceManager.GetString("DGProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity.
        /// </summary>
        public static string DGQuantity {
            get {
                return ResourceManager.GetString("DGQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight.
        /// </summary>
        public static string DGWeight {
            get {
                return ResourceManager.GetString("DGWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Address&quot; is empty!.
        /// </summary>
        public static string ErrorAddress {
            get {
                return ResourceManager.GetString("ErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Client&quot; have wrong format!.
        /// </summary>
        public static string ErrorClient {
            get {
                return ResourceManager.GetString("ErrorClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Date of birth&quot; is empty!.
        /// </summary>
        public static string ErrorDateOfBirth {
            get {
                return ResourceManager.GetString("ErrorDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Date of sale&quot; is empty!.
        /// </summary>
        public static string ErrorDateOfSale {
            get {
                return ResourceManager.GetString("ErrorDateOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid login or password!.
        /// </summary>
        public static string ErrorInvalidLog {
            get {
                return ResourceManager.GetString("ErrorInvalidLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Name&quot; is empty!.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No connection!.
        /// </summary>
        public static string ErrorNoConnect {
            get {
                return ResourceManager.GetString("ErrorNoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have entered nothing!.
        /// </summary>
        public static string ErrorNotEterned {
            get {
                return ResourceManager.GetString("ErrorNotEterned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The field &quot;Phone&quot; is not filled in or not completely filled in!.
        /// </summary>
        public static string ErrorPhone {
            get {
                return ResourceManager.GetString("ErrorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Price&quot; is empty!.
        /// </summary>
        public static string ErrorPriceEmpty {
            get {
                return ResourceManager.GetString("ErrorPriceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Price&quot; have wrong format!.
        /// </summary>
        public static string ErrorPriceFormat {
            get {
                return ResourceManager.GetString("ErrorPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Product&quot; have wrong format!.
        /// </summary>
        public static string ErrorProduct {
            get {
                return ResourceManager.GetString("ErrorProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Production date&quot; is empty!.
        /// </summary>
        public static string ErrorProductionDate {
            get {
                return ResourceManager.GetString("ErrorProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Product name&quot; is empty!.
        /// </summary>
        public static string ErrorProductName {
            get {
                return ResourceManager.GetString("ErrorProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Quantity&quot; is empty!.
        /// </summary>
        public static string ErrorQuantityEmpty {
            get {
                return ResourceManager.GetString("ErrorQuantityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Quantity&quot; have wrong format!.
        /// </summary>
        public static string ErrorQuantityFormat {
            get {
                return ResourceManager.GetString("ErrorQuantityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You entered something wrong!.
        /// </summary>
        public static string ErrorSomethingWrong {
            get {
                return ResourceManager.GetString("ErrorSomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unspecified error!.
        /// </summary>
        public static string ErrorUnspecified {
            get {
                return ResourceManager.GetString("ErrorUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Weight&quot; is empty!.
        /// </summary>
        public static string ErrorWeightEmpty {
            get {
                return ResourceManager.GetString("ErrorWeightEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &quot;Weight&quot; have wrong format!.
        /// </summary>
        public static string ErrorWeightFormat {
            get {
                return ResourceManager.GetString("ErrorWeightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you really want to log out?.
        /// </summary>
        public static string MessageExit {
            get {
                return ResourceManager.GetString("MessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully added!.
        /// </summary>
        public static string MessageSuccessfullAdd {
            get {
                return ResourceManager.GetString("MessageSuccessfullAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully edited!.
        /// </summary>
        public static string MessageSuccessfullEdit {
            get {
                return ResourceManager.GetString("MessageSuccessfullEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address :.
        /// </summary>
        public static string TextAddress {
            get {
                return ResourceManager.GetString("TextAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Client :.
        /// </summary>
        public static string TextClient {
            get {
                return ResourceManager.GetString("TextClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of birth :.
        /// </summary>
        public static string TextDateOfBirth {
            get {
                return ResourceManager.GetString("TextDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of sale :.
        /// </summary>
        public static string TextDateOfSale {
            get {
                return ResourceManager.GetString("TextDateOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter by date :.
        /// </summary>
        public static string TextFilterByDate {
            get {
                return ResourceManager.GetString("TextFilterByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gender :.
        /// </summary>
        public static string TextGender {
            get {
                return ResourceManager.GetString("TextGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language :.
        /// </summary>
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login :.
        /// </summary>
        public static string TextLogin {
            get {
                return ResourceManager.GetString("TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name :.
        /// </summary>
        public static string TextName {
            get {
                return ResourceManager.GetString("TextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing found!.
        /// </summary>
        public static string TextNullSearch {
            get {
                return ResourceManager.GetString("TextNullSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password :.
        /// </summary>
        public static string TextPassword {
            get {
                return ResourceManager.GetString("TextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone :.
        /// </summary>
        public static string TextPhone {
            get {
                return ResourceManager.GetString("TextPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price :.
        /// </summary>
        public static string TextPrice {
            get {
                return ResourceManager.GetString("TextPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product :.
        /// </summary>
        public static string TextProduct {
            get {
                return ResourceManager.GetString("TextProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production date :.
        /// </summary>
        public static string TextProductionDate {
            get {
                return ResourceManager.GetString("TextProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product name :.
        /// </summary>
        public static string TextProductName {
            get {
                return ResourceManager.GetString("TextProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity :.
        /// </summary>
        public static string TextQuantity {
            get {
                return ResourceManager.GetString("TextQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by name :.
        /// </summary>
        public static string TextSearchByName {
            get {
                return ResourceManager.GetString("TextSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by name or product name :.
        /// </summary>
        public static string TextSearchByNameOrPN {
            get {
                return ResourceManager.GetString("TextSearchByNameOrPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by product name :.
        /// </summary>
        public static string TextSearchByProductName {
            get {
                return ResourceManager.GetString("TextSearchByProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight :.
        /// </summary>
        public static string TextWeight {
            get {
                return ResourceManager.GetString("TextWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Furniture store &quot;Home comfort&quot;.
        /// </summary>
        public static string TitleFurnitureStore {
            get {
                return ResourceManager.GetString("TitleFurnitureStore", resourceCulture);
            }
        }
    }
}
